version: '3.4'
services:
  ### Nginx Web Container #######################################
  nginx:
    image: nginx:1.13.1-alpine
    ports:
      - "80:80"
      - "443:443"
    #source code container
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/cert:/etc/nginx/cert/
    depends_on:
      - php-fpm:php-fpm
    networks:
     - overlay
    deploy:
      mode: replicated
      replicas: 1

  ### PHP-FPM Container #######################################
  php-fpm:
    image: bravist/php-fpm-alpine-aliyun-app:1.14
    ports:
      - "9000:9000"
    volumes: 
      - ./www:/usr/share/nginx/html
    networks:
      - overlay
    depends_on:
      - mariadb
    extra_hosts:
      - "${PHP_FPM_DOMAIN}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN2}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN3}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN4}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN5}:${NGINX_WEB_SERVER_IP}"
    env_file:
      - .env
    deploy:
      placement:
        constraints: [node.role == manager]


  ### MariaDB Container #######################################
  # MariaDB - One of the most popular database servers. Made by the original developers of MySQL. Guaranteed to stay open source.
  mariadb:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=developer
    networks:
      - overlay
    deploy:
      placement:
        constraints: [node.role == manager]

### Networks Setup ############################################
networks:
  overlay:
